branches:
  only:
    - master
language: ruby
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - 1.9.3
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - haveged
rvm:
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - jruby-9.1.5.0
